# Cloud Build configuration for agentic-flow
# Builds optimized Docker image with caching

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/agentic-flow:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/agentic-flow:latest'
      - '-f'
      - 'docker/base/Dockerfile'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/agentic-flow:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'
    timeout: 1200s

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/agentic-flow:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/agentic-flow:latest'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

# Images to store in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/agentic-flow:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/agentic-flow:latest'

# Timeout for the entire build
timeout: 1800s
