# Prometheus Configuration for CRISPR-Cas13 Pipeline
# Version: 1.0.0

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'crispr-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Load rules
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # ==================================================
  # API Gateway
  # ==================================================
  - job_name: 'api-gateway'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - crispr-production
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: api-gateway
        action: keep
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
    metrics_path: /metrics
    scrape_interval: 10s

  # ==================================================
  # Processing Services
  # ==================================================
  - job_name: 'alignment-service'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - crispr-production
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: alignment-service
        action: keep
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
    metrics_path: /metrics

  - job_name: 'off-target-service'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - crispr-production
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: off-target-service
        action: keep
    metrics_path: /metrics

  - job_name: 'diff-expr-service'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - crispr-production
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: diff-expr-service
        action: keep
    metrics_path: /metrics

  # ==================================================
  # Databases
  # ==================================================
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics
    scrape_interval: 30s

  # ==================================================
  # Message Queue
  # ==================================================
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    metrics_path: /metrics
    scrape_interval: 15s

  # ==================================================
  # Object Storage
  # ==================================================
  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 30s

  # ==================================================
  # Kubernetes Infrastructure
  # ==================================================
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  # ==================================================
  # Nginx Ingress
  # ==================================================
  - job_name: 'nginx-ingress'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - ingress-nginx
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        regex: ingress-nginx
        action: keep
    metrics_path: /metrics
    scrape_interval: 10s

  # ==================================================
  # Blackbox Exporter (HTTP probes)
  # ==================================================
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.crispr.example.com/health
        - https://api.crispr.example.com/ready
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
    scrape_interval: 30s

  # ==================================================
  # Self-monitoring
  # ==================================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Storage configuration
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 30d
    retention.size: 500GB
