version: '3.8'

services:
  agentdb-validation:
    build:
      context: .
      dockerfile: Dockerfile.validation
    container_name: agentdb-v1.3.0-validation
    environment:
      - NODE_ENV=test
      - CI=true
    volumes:
      - ./validation-reports:/app/reports
    networks:
      - agentdb-validation-net

  agentdb-mcp-test:
    build:
      context: .
      dockerfile: Dockerfile.validation
    container_name: agentdb-mcp-integration-test
    command: >
      sh -c "
        echo 'Testing MCP Tools Integration...' &&
        node dist/mcp/agentdb-mcp-server.js &
        MCP_PID=\$! &&
        sleep 3 &&
        kill \$MCP_PID &&
        echo 'MCP server test completed'
      "
    environment:
      - NODE_ENV=production
    networks:
      - agentdb-validation-net

networks:
  agentdb-validation-net:
    driver: bridge
