apiVersion: apps/v1
kind: Deployment
metadata:
  name: climate-prediction-canary
  namespace: production
  labels:
    app: climate-prediction
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: climate-prediction
      version: canary
  template:
    metadata:
      labels:
        app: climate-prediction
        version: canary
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: climate-prediction
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000

      containers:
      - name: climate-prediction
        image: ghcr.io/yourorg/climate-prediction:canary
        imagePullPolicy: Always

        ports:
        - name: http
          containerPort: 8080
          protocol: TCP

        env:
        - name: RUST_LOG
          value: "debug"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8080"
        - name: CANARY_DEPLOYMENT
          value: "true"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: climate-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: climate-secrets
              key: redis-url
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: climate-secrets
              key: openweather-api-key

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL

        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/cache

      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: climate-prediction-canary
  namespace: production
  labels:
    app: climate-prediction
    version: canary
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: climate-prediction
    version: canary
