apiVersion: v1
kind: Service
metadata:
  name: climate-prediction
  namespace: production
  labels:
    app: climate-prediction
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 8080
    protocol: TCP
  selector:
    app: climate-prediction

---
apiVersion: v1
kind: Service
metadata:
  name: climate-prediction-headless
  namespace: production
  labels:
    app: climate-prediction
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: climate-prediction

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: climate-config
  namespace: production
data:
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  MAX_CONNECTIONS: "100"
  CACHE_TTL: "3600"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: climate-prediction
  namespace: production
  labels:
    app: climate-prediction

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: climate-prediction
  namespace: production
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: climate-prediction
  namespace: production
subjects:
- kind: ServiceAccount
  name: climate-prediction
  namespace: production
roleRef:
  kind: Role
  name: climate-prediction
  apiGroup: rbac.authorization.k8s.io
