# fly.toml app configuration file generated for agentic-llm-phi4 on 2025-10-03T23:11:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agentic-llm-phi4'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  CUDA_VISIBLE_DEVICES = '0'
  HF_HOME = '/app/models'
  PYTHONUNBUFFERED = '1'
  TRANSFORMERS_CACHE = '/app/models'

[[mounts]]
  source = 'phi4_storage'
  destination = '/app/storage'
  initial_size = '150gb'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '30s'

[[vm]]
  size = 'a100-40gb'
  memory = '32gb'
  cpus = 8

[[metrics]]
  port = 9090
  path = '/metrics'
