apiVersion: apps/v1
kind: Deployment
metadata:
  name: alignment-service
  namespace: crispr-production
  labels:
    app: alignment-service
    version: v1.0.0
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: alignment-service
  template:
    metadata:
      labels:
        app: alignment-service
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: alignment-service
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role
                operator: In
                values:
                - compute-intensive
      tolerations:
      - key: "compute-intensive"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: alignment-worker
        image: crispr-registry.io/alignment-service:v1.0.0
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKERS
          value: "kafka-0.kafka:9092,kafka-1.kafka:9092,kafka-2.kafka:9092"
        - name: KAFKA_GROUP_ID
          value: "alignment-workers"
        - name: KAFKA_TOPICS
          value: "jobs.alignment"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: url
        - name: MINIO_ENDPOINT
          value: "http://minio:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret_key
        - name: REFERENCE_GENOME
          value: "/data/genomes/rheMac10/bowtie2_index"
        - name: BOWTIE2_THREADS
          value: "8"
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
            ephemeral-storage: "100Gi"
          limits:
            cpu: "8"
            memory: "32Gi"
            ephemeral-storage: "200Gi"
        volumeMounts:
        - name: reference-genomes
          mountPath: /data/genomes
          readOnly: true
        - name: tmp
          mountPath: /tmp
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
      volumes:
      - name: reference-genomes
        persistentVolumeClaim:
          claimName: reference-genomes-pvc
          readOnly: true
      - name: tmp
        emptyDir:
          sizeLimit: 150Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alignment-service
  namespace: crispr-production
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: alignment-service-hpa
  namespace: crispr-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alignment-service
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: External
    external:
      metric:
        name: kafka_consumer_lag
        selector:
          matchLabels:
            topic: jobs.alignment
      target:
        type: Value
        value: "100"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reference-genomes-pvc
  namespace: crispr-production
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd
