apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: crispr-production
data:
  postgresql.conf: |
    # Connection Settings
    max_connections = 200
    shared_buffers = 4GB
    effective_cache_size = 12GB

    # Write Performance
    wal_buffers = 16MB
    checkpoint_timeout = 10min
    max_wal_size = 4GB

    # Query Optimization
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 32MB
    maintenance_work_mem = 1GB

    # Logging
    log_destination = 'stderr'
    logging_collector = on
    log_directory = 'pg_log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_statement = 'mod'
    log_duration = on
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '

    # Replication
    wal_level = replica
    max_wal_senders = 10
    wal_keep_size = 4GB
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: crispr-production
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: "crispr_cas13"
        - name: POSTGRES_USER
          value: "crispr_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-config
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
        resources:
          requests:
            cpu: "2"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "16Gi"
      volumes:
      - name: postgres-config
        configMap:
          name: postgres-config
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fast-ssd
      resources:
        requests:
          storage: 500Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: crispr-production
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
  namespace: crispr-production
type: Opaque
stringData:
  password: "changeme-in-production"
