apiVersion: v2
name: climate-prediction
description: A Helm chart for Climate Prediction API
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - climate
  - weather
  - prediction
  - api
  - rust
home: https://github.com/yourorg/climate-prediction
sources:
  - https://github.com/yourorg/climate-prediction
maintainers:
  - name: DevOps Team
    email: devops@example.com
icon: https://example.com/climate-icon.png
